//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MageWarsWebSite.Web.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GlobalRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MageWarsWebSite.Web.App_LocalResources.GlobalRes", typeof(GlobalRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Card.
        /// </summary>
        public static string AddCard {
            get {
                return ResourceManager.GetString("AddCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Card Type.
        /// </summary>
        public static string AddCardType {
            get {
                return ResourceManager.GetString("AddCardType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add card types by parse.
        /// </summary>
        public static string AddCardTypesByParse {
            get {
                return ResourceManager.GetString("AddCardTypesByParse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Mage.
        /// </summary>
        public static string AddMage {
            get {
                return ResourceManager.GetString("AddMage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new card: .
        /// </summary>
        public static string AddNewCard {
            get {
                return ResourceManager.GetString("AddNewCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new card type.
        /// </summary>
        public static string AddNewCardType {
            get {
                return ResourceManager.GetString("AddNewCardType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new card type by parse.
        /// </summary>
        public static string AddNewCardTypesByParse {
            get {
                return ResourceManager.GetString("AddNewCardTypesByParse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new mage:.
        /// </summary>
        public static string AddNewMage {
            get {
                return ResourceManager.GetString("AddNewMage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new school.
        /// </summary>
        public static string AddNewSchool {
            get {
                return ResourceManager.GetString("AddNewSchool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new schools by parse.
        /// </summary>
        public static string AddNewSchoolsByParse {
            get {
                return ResourceManager.GetString("AddNewSchoolsByParse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new sub type.
        /// </summary>
        public static string AddNewSubType {
            get {
                return ResourceManager.GetString("AddNewSubType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new sub types by parse.
        /// </summary>
        public static string AddNewSubTypesByParse {
            get {
                return ResourceManager.GetString("AddNewSubTypesByParse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add school.
        /// </summary>
        public static string AddSchool {
            get {
                return ResourceManager.GetString("AddSchool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add schools by parse.
        /// </summary>
        public static string AddSchoolsByParse {
            get {
                return ResourceManager.GetString("AddSchoolsByParse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add sub type.
        /// </summary>
        public static string AddSubType {
            get {
                return ResourceManager.GetString("AddSubType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add sub types by parse.
        /// </summary>
        public static string AddSubTypesByParse {
            get {
                return ResourceManager.GetString("AddSubTypesByParse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to cards page.
        /// </summary>
        public static string BackToCards {
            get {
                return ResourceManager.GetString("BackToCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to card types page.
        /// </summary>
        public static string BackToCardTypes {
            get {
                return ResourceManager.GetString("BackToCardTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to mages page.
        /// </summary>
        public static string BackToMages {
            get {
                return ResourceManager.GetString("BackToMages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First page.
        /// </summary>
        public static string Begin {
            get {
                return ResourceManager.GetString("Begin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred when adding the new card .
        /// </summary>
        public static string CardAddError {
            get {
                return ResourceManager.GetString("CardAddError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card with id {0} was successfully added.
        /// </summary>
        public static string CardAddSuccessFormat {
            get {
                return ResourceManager.GetString("CardAddSuccessFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error. card with such id - {0} was not found!.
        /// </summary>
        public static string CardBadIdErrorFormat {
            get {
                return ResourceManager.GetString("CardBadIdErrorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred because someone changed Id when editing Card.
        /// </summary>
        public static string CardChangedIdError {
            get {
                return ResourceManager.GetString("CardChangedIdError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred when deleting the card with id {0}.
        /// </summary>
        public static string CardDeleteErrorFormat {
            get {
                return ResourceManager.GetString("CardDeleteErrorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card with id {0} was successfully deleted.
        /// </summary>
        public static string CardDeleteSuccessFormat {
            get {
                return ResourceManager.GetString("CardDeleteSuccessFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card image:.
        /// </summary>
        public static string CardImage {
            get {
                return ResourceManager.GetString("CardImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card with id {0} have not found.
        /// </summary>
        public static string CardNotFoundErrorFormat {
            get {
                return ResourceManager.GetString("CardNotFoundErrorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cards.
        /// </summary>
        public static string Cards {
            get {
                return ResourceManager.GetString("Cards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred when adding the new card type.
        /// </summary>
        public static string CardTypeAddError {
            get {
                return ResourceManager.GetString("CardTypeAddError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card type with id {0} was successfully added.
        /// </summary>
        public static string CardTypeAddSuccessFormat {
            get {
                return ResourceManager.GetString("CardTypeAddSuccessFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred when deleting the card type with id {0}.
        /// </summary>
        public static string CardTypeDeleteErrorFormat {
            get {
                return ResourceManager.GetString("CardTypeDeleteErrorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card type with id {0} was successfully deleted.
        /// </summary>
        public static string CardTypeDeleteSuccessFormat {
            get {
                return ResourceManager.GetString("CardTypeDeleteSuccessFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card type with id {0} have not found.
        /// </summary>
        public static string CardTypeNotFoundErrorFormat {
            get {
                return ResourceManager.GetString("CardTypeNotFoundErrorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card types.
        /// </summary>
        public static string CardTypes {
            get {
                return ResourceManager.GetString("CardTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred when adding some of the new card types.
        /// </summary>
        public static string CardTypesAddError {
            get {
                return ResourceManager.GetString("CardTypesAddError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All parsed card types was successfully added.
        /// </summary>
        public static string CardTypesAddSuccess {
            get {
                return ResourceManager.GetString("CardTypesAddSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred when updating the card type with id {0}.
        /// </summary>
        public static string CardTypeUpdateErrorFormat {
            get {
                return ResourceManager.GetString("CardTypeUpdateErrorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card type with id {0} was successfully updated.
        /// </summary>
        public static string CardTypeUpdateSuccessFormat {
            get {
                return ResourceManager.GetString("CardTypeUpdateSuccessFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred when updating the card with id {0}.
        /// </summary>
        public static string CardUpdateErrorFormat {
            get {
                return ResourceManager.GetString("CardUpdateErrorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card with id {0} was successfully updated.
        /// </summary>
        public static string CardUpdateSuccessFormat {
            get {
                return ResourceManager.GetString("CardUpdateSuccessFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Page.
        /// </summary>
        public static string CurrentPage {
            get {
                return ResourceManager.GetString("CurrentPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Card.
        /// </summary>
        public static string DeleteCard {
            get {
                return ResourceManager.GetString("DeleteCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Card Type.
        /// </summary>
        public static string DeleteCardType {
            get {
                return ResourceManager.GetString("DeleteCardType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Mage.
        /// </summary>
        public static string DeleteMage {
            get {
                return ResourceManager.GetString("DeleteMage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete scool.
        /// </summary>
        public static string DeleteSchool {
            get {
                return ResourceManager.GetString("DeleteSchool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete sub type.
        /// </summary>
        public static string DeleteSubType {
            get {
                return ResourceManager.GetString("DeleteSubType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Card.
        /// </summary>
        public static string EditCard {
            get {
                return ResourceManager.GetString("EditCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Card Type.
        /// </summary>
        public static string EditCardType {
            get {
                return ResourceManager.GetString("EditCardType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Mage.
        /// </summary>
        public static string EditMage {
            get {
                return ResourceManager.GetString("EditMage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit school.
        /// </summary>
        public static string EditSchool {
            get {
                return ResourceManager.GetString("EditSchool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit sub type.
        /// </summary>
        public static string EditSubType {
            get {
                return ResourceManager.GetString("EditSubType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Page.
        /// </summary>
        public static string End {
            get {
                return ResourceManager.GetString("End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FileName is already exist! Please, specify another..
        /// </summary>
        public static string FileNameAlreadyExistModelError {
            get {
                return ResourceManager.GetString("FileNameAlreadyExistModelError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must pick an image!.
        /// </summary>
        public static string ImageRequiredModelError {
            get {
                return ResourceManager.GetString("ImageRequiredModelError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred when adding the new mage.
        /// </summary>
        public static string MageAddError {
            get {
                return ResourceManager.GetString("MageAddError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mage with id {0} was successfully added.
        /// </summary>
        public static string MageAddSuccessFormat {
            get {
                return ResourceManager.GetString("MageAddSuccessFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred because someone changed Id when editing Mage.
        /// </summary>
        public static string MageChangedIdError {
            get {
                return ResourceManager.GetString("MageChangedIdError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred when deleting the mage with id {0}.
        /// </summary>
        public static string MageDeleteErrorFormat {
            get {
                return ResourceManager.GetString("MageDeleteErrorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mage with id {0} was successfully deleted.
        /// </summary>
        public static string MageDeleteSuccessFormat {
            get {
                return ResourceManager.GetString("MageDeleteSuccessFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mage description image:.
        /// </summary>
        public static string MageDescriptionImage {
            get {
                return ResourceManager.GetString("MageDescriptionImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mage image:.
        /// </summary>
        public static string MageImage {
            get {
                return ResourceManager.GetString("MageImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mage name is already exist! Please, specify another..
        /// </summary>
        public static string MageNameAlreadyExistModelError {
            get {
                return ResourceManager.GetString("MageNameAlreadyExistModelError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mage with id {0} have not found.
        /// </summary>
        public static string MageNotFoundErrorFormat {
            get {
                return ResourceManager.GetString("MageNotFoundErrorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mages.
        /// </summary>
        public static string Mages {
            get {
                return ResourceManager.GetString("Mages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred when updating the mage with id {0}.
        /// </summary>
        public static string MageUpdateErrorFormat {
            get {
                return ResourceManager.GetString("MageUpdateErrorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mage with id {0} was successfully updated.
        /// </summary>
        public static string MageUpdateSuccessFormat {
            get {
                return ResourceManager.GetString("MageUpdateSuccessFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Page.
        /// </summary>
        public static string MainPage {
            get {
                return ResourceManager.GetString("MainPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Page.
        /// </summary>
        public static string NextPage {
            get {
                return ResourceManager.GetString("NextPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, choose image for mage description:.
        /// </summary>
        public static string PleaseChooseDescriptionImage {
            get {
                return ResourceManager.GetString("PleaseChooseDescriptionImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, choose image for mage:.
        /// </summary>
        public static string PleaseChooseHeroImage {
            get {
                return ResourceManager.GetString("PleaseChooseHeroImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, choose image:.
        /// </summary>
        public static string PleaseChooseImage {
            get {
                return ResourceManager.GetString("PleaseChooseImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous page.
        /// </summary>
        public static string PrevPage {
            get {
                return ResourceManager.GetString("PrevPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred when adding the new school.
        /// </summary>
        public static string SchoolAddError {
            get {
                return ResourceManager.GetString("SchoolAddError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to School with id {0} was successfully added.
        /// </summary>
        public static string SchoolAddSuccessFormat {
            get {
                return ResourceManager.GetString("SchoolAddSuccessFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred when deleting the school with id {0}.
        /// </summary>
        public static string SchoolDeleteErrorFormat {
            get {
                return ResourceManager.GetString("SchoolDeleteErrorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to School with id {0} was successfully deleted.
        /// </summary>
        public static string SchoolDeleteSuccessFormat {
            get {
                return ResourceManager.GetString("SchoolDeleteSuccessFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If level not specifying, level unlimited.
        /// </summary>
        public static string SchoolLevelTooltip {
            get {
                return ResourceManager.GetString("SchoolLevelTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to School with id {0} have not found.
        /// </summary>
        public static string SchoolNotFoundErrorFormat {
            get {
                return ResourceManager.GetString("SchoolNotFoundErrorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must choose at least one school!.
        /// </summary>
        public static string SchoolRequiredModelError {
            get {
                return ResourceManager.GetString("SchoolRequiredModelError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schools.
        /// </summary>
        public static string Schools {
            get {
                return ResourceManager.GetString("Schools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred when adding some of the new schools.
        /// </summary>
        public static string SchoolsAddError {
            get {
                return ResourceManager.GetString("SchoolsAddError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All parsed schools was successfully added.
        /// </summary>
        public static string SchoolsAddSuccess {
            get {
                return ResourceManager.GetString("SchoolsAddSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred when updating the school with id {0}.
        /// </summary>
        public static string SchoolUpdateErrorFormat {
            get {
                return ResourceManager.GetString("SchoolUpdateErrorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to School with id {0} was successfully updated.
        /// </summary>
        public static string SchoolUpdateSuccessFormat {
            get {
                return ResourceManager.GetString("SchoolUpdateSuccessFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Card.
        /// </summary>
        public static string SelectedCard {
            get {
                return ResourceManager.GetString("SelectedCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Mage.
        /// </summary>
        public static string SelectedMage {
            get {
                return ResourceManager.GetString("SelectedMage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit Card.
        /// </summary>
        public static string SubmitCard {
            get {
                return ResourceManager.GetString("SubmitCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit card type.
        /// </summary>
        public static string SubmitCardType {
            get {
                return ResourceManager.GetString("SubmitCardType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit changes.
        /// </summary>
        public static string SubmitChanges {
            get {
                return ResourceManager.GetString("SubmitChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit mage.
        /// </summary>
        public static string SubmitMage {
            get {
                return ResourceManager.GetString("SubmitMage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit school.
        /// </summary>
        public static string SubmitSchool {
            get {
                return ResourceManager.GetString("SubmitSchool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit sub type.
        /// </summary>
        public static string SubmitSubType {
            get {
                return ResourceManager.GetString("SubmitSubType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred when adding the new sub type.
        /// </summary>
        public static string SubTypeAddError {
            get {
                return ResourceManager.GetString("SubTypeAddError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub type with id {0} was successfully added.
        /// </summary>
        public static string SubTypeAddSuccessFormat {
            get {
                return ResourceManager.GetString("SubTypeAddSuccessFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred when deleting the sub type with id {0}.
        /// </summary>
        public static string SubTypeDeleteErrorFormat {
            get {
                return ResourceManager.GetString("SubTypeDeleteErrorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub type with id {0} was successfully deleted.
        /// </summary>
        public static string SubTypeDeleteSuccessFormat {
            get {
                return ResourceManager.GetString("SubTypeDeleteSuccessFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub type with id {0} have not found.
        /// </summary>
        public static string SubTypeNotFoundErrorFormat {
            get {
                return ResourceManager.GetString("SubTypeNotFoundErrorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must choose at least one subtype!.
        /// </summary>
        public static string SubTypeRequiredModelError {
            get {
                return ResourceManager.GetString("SubTypeRequiredModelError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub types.
        /// </summary>
        public static string SubTypes {
            get {
                return ResourceManager.GetString("SubTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred when adding some of the new sub types.
        /// </summary>
        public static string SubTypesAddError {
            get {
                return ResourceManager.GetString("SubTypesAddError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All parsed sub types was successfully added.
        /// </summary>
        public static string SubTypesAddSuccess {
            get {
                return ResourceManager.GetString("SubTypesAddSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred when updating the sub type with id {0}.
        /// </summary>
        public static string SubTypeUpdateErrorFormat {
            get {
                return ResourceManager.GetString("SubTypeUpdateErrorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub type with id {0} was successfully updated.
        /// </summary>
        public static string SubTypeUpdateSuccessFormat {
            get {
                return ResourceManager.GetString("SubTypeUpdateSuccessFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must choose at least one type!.
        /// </summary>
        public static string TypeRequiredModelError {
            get {
                return ResourceManager.GetString("TypeRequiredModelError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Types.
        /// </summary>
        public static string Types {
            get {
                return ResourceManager.GetString("Types", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Card Page.
        /// </summary>
        public static string ViewCardPage {
            get {
                return ResourceManager.GetString("ViewCardPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Mage Page.
        /// </summary>
        public static string ViewMagePage {
            get {
                return ResourceManager.GetString("ViewMagePage", resourceCulture);
            }
        }
    }
}
